kind: Service                             
apiVersion: v1
metadata:
  name: mrdevops
  labels:
    app: mrdevops
spec:
  type: NodePort 
  ports:
    - port: 8080                               
      targetPort: 8000                    
      nodePort: 31200
  selector:
    app: mrdevops                    
                  